### ISSUE TITLE
Broken build on 0.2.x branch

### ISSUE THREAD

**Issue by cjackett** [morphocluster/morphocluster#92]
Hi Simon,

I watched your excellent presentation about MorphoCluster as the Marine Imaging Workshop in 2022 and have been looking forward to trying it out on a FlowCam dataset we're accumulating. Unfortunately, I've been unable to build the 0.2.x branch so far - please see bug report below:

**Describe the bug**
Unable to build and run the 0.2.x branch due to error in flask_sqlalchemy package.

**To Reproduce**
Clone the repo, build and run the 0.2.x branch

**Expected behavior**
Successfully build and run MorphoCluster

**Screenshots**
![image](https://github.com/morphocluster/morphocluster/assets/8358631/f8dbc8c2-bcc2-4b8e-a671-24f5b28d2ed1)

**MorphoCluster Version**
0.2.x branch

**Additional context**
AttributeError: module 'sqlalchemy' has no attribute '__all__'

It looks like there's an issue with the flask_sqlalchemy package that may have arisen due to a new version of that package perhaps. I've exec'ed into the container and it looks like Flask-SQLAlchemy==2.5.1 is installed, and I've updated that package but still get the same error.

**Comment by moi90** [comment]
Hi @cjackett, thanks for your bug report! (This is a common problem which I'm planning to address in the next release.)

You could use the pre-built (but slightly outdated) Docker image to avoid building it yourself:

For that, you replace the build section in the docker-compose file with the pre-built image:

```diff
- build:
-  context: .
-  dockerfile: docker/morphocluster/Dockerfile
+ image: morphocluster/morphocluster:0.2.1
```

Does that work for you?

**Comment by cjackett** [comment]
Hi @moi90 - thank you, working nicely now.

**Comment by moi90** [comment]
Great! I'll close this issue then.

Maybe you want to join the [MorphoCluster user group](https://groups.google.com/g/morphocluster)?
